steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'docker/prod/Dockerfile'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}', 
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:latest', 
      '--region', '${_REGION}', 
      '--platform', 'managed', 
      '--allow-unauthenticated'
    ]

# Substitution variables
substitutions:
  _SERVICE_NAME: 'ntusu-itc-backend'
  _REGION: 'asia-southeast1'

options:
  logging: CLOUD_LOGGING_ONLY